name: Check links daily

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: '-c .github/lychee.toml ./content.md'
          jobSummary: false

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link-checker

      - name: Update Issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Broken links detected!
          issue-number: "${{ steps.link-checker-issue.outputs.issue-number }}"
          content-filepath: ./lychee/out.md
          token: ${{secrets.GITHUB_TOKEN}}
          labels: |
            link-checker
